### ISSUE TITLE
Bug: Testchart does not properly show diff for multiple resources defined in same yaml file

### ISSUE THREAD

**Issue by alexstojda** [silphid/testchart#1]
If a chart has multiple resources defined in the same template file, and there is a diff in both, test chart only renders the diff for one of the resources in the template file.

The expected file is generated with both resources, only the diff is incorrect. 

## To reproduce:
1. Create a helm chart with 2 resources defined in the same file. ex:
`templates/configmap.yaml`
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: foobar-1
data:
  foo: bar
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: foobar-2
data:
  bar: foo
```

2. Create a test and generate the expected file.
3. Make a modification in both resources, and run `testchart run` to view the diff
